spring:
  application:
    name: iot-sensor
#  integration:
#    mqtt:
#      broker-url: tcp://mosquitto:1883
#      client-id: iot-sensor-server-client

management:
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  level:
    org.springframework.integration.mqtt: DEBUG
    org.eclipse.paho: DEBUG